version: '{build}'

branches:
  only:
  - master

init:
    - cmd: git config --global core.autocrlf true

artifacts:
  - path: FWTL.Core.Common\nupkgs\*.nupkg
    name: nuget-core
  - path: FWTL.Infrastructure.Common\nupkgs\*.nupkg
    name: nuget-infrastructure

cache:
  - packages -> FWTL.Core.Common.csproj, FWTL.Infrastructure.Common.csproj

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore FWTL.sln

build_script:
  - cmd: dotnet build FWTL.sln --no-restore 

after_build:
- ps: >-
    if(!$env:APPVEYOR_REPO_TAG_NAME)
    {
        dotnet pack FWTL.Core.Common/FWTL.Core.Common.csproj --no-build --output nupkgs -p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
        dotnet pack FWTL.Infrastructure.Common/FWTL.Infrastructure.Common.csproj --no-build --output nupkgs -p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
    }

nuget:
    disable_publish_on_pr: true
    
deploy: 
    - provider: NuGet
      api_key:
          secure: 55pO38HXY6SYCcSyEDy6XVdpDgJOasIlIp/MIOlwZoH+rEj4fN+hMabmP+0wJyt5
      artifact: nuget-core
      on:
          appveyor_repo_tag: true
    - provider: NuGet
      api_key:
          secure: 55pO38HXY6SYCcSyEDy6XVdpDgJOasIlIp/MIOlwZoH+rEj4fN+hMabmP+0wJyt5
      artifact: nuget-infrastructure
      on:
          appveyor_repo_tag: true
  
  
notifications:
- provider: Email
  to:
  - a@gmail.info
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false