version: '{build}'

branches:
  only:
  - master

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

    - cmd: git config --global core.autocrlf true

artifacts:
  - path: FWTL.Core\nupkgs\*.nupkg
    name: nuget-core
  - path: FWTL.Infrastructure\nupkgs\*.nupkg
    name: nuget-infrastructure

cache:
  - packages -> FWTL.Core.csproj, FWTL.Infrastructure.csproj

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -no-restore

after_build:
- ps: >-
    dotnet pack --no-build --output nupkgs -p:PackageVersion='1.0.0'

nuget:
    disable_publish_on_pr: true
    
# deploy:
#     - provider: GitHub
#       release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
#       tag: $(APPVEYOR_REPO_TAG_NAME)
#       description: ''
#       prerelease: $(IsPreRelease)
#       artifact: Inquirer
#       auth_token:
#           secure: JnUtQ9HEoqyYkHVkj5he8tbRauph96orT9i0eiyAB4R9a9g2hW4Mvm1SYDxsUvUg
#       on:
#           appveyor_repo_tag_name: /\d+\.\d+\.\d+(-{0,1})(alpha|$)/
#           appveyor_repo_tag: true
          
#     - provider: NuGet
#       api_key:
#           secure: jAS5nyIwacqXwMQl7CAi76q0+NAH3A3fGdvY8SCY+AfnNwSAooWfj4Bym6MPHdDF
#       artifact: NuGet
#       on:
#           appveyor_repo_tag_name: /\d+\.\d+\.\d+(-{0,1})(alpha|$)/
#           appveyor_repo_tag: true
  
  
notifications:
- provider: Email
  to:
  - golaszewski.a@gmail.info
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false